Championship.create(:id => 5, :name => "Campeonato Fórmula SAC", :year => 2015, :category_id => 3)
Championship.create(:id => 7, :name => "Campeonato Karting 125cc", :year => 2015, :category_id => 2, :sub_category => "Super A")
Championship.create(:id => 8, :name => "Campeonato Karting 125cc", :year => 2015, :category_id => 2, :sub_category => "A")
Championship.create(:id => 1, :name => "Campeonato Turismo Pista SAC", :year => 2015, :category_id => 1)
Championship.create(:id => 2, :name => "Campeonato Turismo Pista SAC", :year => 2014, :one_id => 2, :two_id => 1, :three_id => 5, :category_id => 1)
Championship.create(:id => 4, :name => "Campeonato Fórmula SAC", :year => 2014, :one_id => 23, :two_id => 22, :three_id => 25, :category_id => 3)
Championship.create(:id => 6, :name => "Campeonato Karting 125cc", :year => 2014, :one_id => 33, :two_id => 39, :three_id => 35, :category_id => 2)
Championship.create(:id => 3, :name => "Campeonato Turismo Pista SAC", :year => 2013, :one_id => 5, :two_id => 2, :three_id => 3, :category_id => 1)
