Pilot.create(:id => 36, :full_name => "Alejo  Parentini", :team => "JM Competición", :car => "Kart 125cc", :city => "Salto", :first_name => "Alejo ", :last_name => "Parentini", :active => true)
Pilot.create(:id => 12, :full_name => "Andrés Berreta", :team => "-", :car => "Gol G2 1.6", :city => "Salto", :first_name => "Andrés", :last_name => "Berreta", :active => false)
Pilot.create(:id => 33, :full_name => "Ariel Bidart", :car => "Kart 125cc", :city => "Salto", :first_name => "Ariel", :last_name => "Bidart", :active => true)
Pilot.create(:id => 30, :full_name => "Arturo  Campos", :team => "-", :car => "Formula VW", :city => "Paysandú", :first_name => "Arturo ", :last_name => "Campos", :active => true)
Pilot.create(:id => 6, :full_name => "Bruno Mori", :team => "JM Competición", :car => "Gol G2 1.6", :city => "Salto", :first_name => "Bruno", :last_name => "Mori", :active => true)
Pilot.create(:id => 62, :full_name => "Carlos Broli", :car => "Kart 125cc", :first_name => "Carlos", :last_name => "Broli", :active => true)
Pilot.create(:id => 4, :full_name => "Cesar Piastri", :team => "Mecánica Senna", :car => "Amazon G1 1.6", :city => "Salto", :first_name => "Cesar", :last_name => "Piastri", :active => true)
Pilot.create(:id => 17, :full_name => "Daniel Constantin", :team => "-", :car => "Gol G1 1.6", :city => "Salto", :first_name => "Daniel", :last_name => "Constantin", :active => false)
Pilot.create(:id => 25, :full_name => "Diego  Sena", :team => "-", :car => "Formula VW", :city => "Salto", :first_name => "Diego ", :last_name => "Sena", :active => false)
Pilot.create(:id => 53, :full_name => "Emiliano Correa", :car => "Kart 125cc", :city => "Bella Unión", :first_name => "Emiliano", :last_name => "Correa", :active => true)
Pilot.create(:id => 38, :full_name => "Enrrique Gimenez", :car => "Kart 125cc", :city => "Salto", :first_name => "Enrrique", :last_name => "Gimenez", :active => true)
Pilot.create(:id => 18, :full_name => "Eriberto Osorio", :team => "-", :car => "Amazon G1 1.6", :city => "Rivera", :first_name => "Eriberto", :last_name => "Osorio", :active => true)
Pilot.create(:id => 60, :full_name => "Ernesto Barcia", :team => "JM Competición", :car => "Kart 125cc", :city => "Salto", :first_name => "Ernesto", :last_name => "Barcia", :active => true)
Pilot.create(:id => 47, :full_name => "Ezequiel Borba", :car => "Kart 125cc", :city => "Salto", :first_name => "Ezequiel", :last_name => "Borba", :active => true)
Pilot.create(:id => 56, :full_name => "Felix De La Carrera", :car => "Kart 125cc", :first_name => "Felix", :last_name => "De La Carrera", :active => true)
Pilot.create(:id => 61, :full_name => "Fernando Guerra", :car => "Kart 125cc", :first_name => "Fernando", :last_name => "Guerra", :active => true)
Pilot.create(:id => 44, :full_name => "Francisco Freitas", :car => "Kart 125cc", :city => "Salto", :first_name => "Francisco", :last_name => "Freitas", :active => true)
Pilot.create(:id => 26, :full_name => "Gabino Franco F.", :team => "Dalloglio ", :car => "Formula VW", :city => "Salto", :first_name => "Gabino", :last_name => "Franco F.", :active => true)
Pilot.create(:id => 27, :full_name => "Gabriel  Brizuela", :team => "-", :car => "Formula VW", :city => "Salto", :first_name => "Gabriel ", :last_name => "Brizuela", :active => false)
Pilot.create(:id => 66, :full_name => "Gastón Generali", :car => "Kart 125cc", :first_name => "Gastón", :last_name => "Generali", :active => true)
Pilot.create(:id => 69, :full_name => "Gerardo Ovseiuk", :car => "Kart 125cc", :city => "Paysandú", :first_name => "Gerardo", :last_name => "Ovseiuk", :active => true)
Pilot.create(:id => 1, :full_name => "Germán Fagalde", :team => "HFP Competición", :car => "Amazon G1 1.6", :city => "Salto", :first_name => "Germán", :last_name => "Fagalde", :birth_date => Fri, 02 May 1986, :active => true)
Pilot.create(:id => 21, :full_name => "Guillermo Lugo", :team => "-", :car => "Gol G1 1.6", :city => "Tacuarembó", :first_name => "Guillermo", :last_name => "Lugo", :active => false)
Pilot.create(:id => 59, :full_name => "Gustavo Boksar", :car => "Kart 125cc", :first_name => "Gustavo", :last_name => "Boksar", :active => true)
Pilot.create(:id => 10, :full_name => "Guzmán Errea", :team => "Tucan Racing", :car => "Gol G1 1.8", :city => "Salto", :first_name => "Guzmán", :last_name => "Errea", :active => true)
Pilot.create(:id => 7, :full_name => "Ignacio Alonso", :team => "-", :car => "Gol G2 1.8", :city => "Tacuarembo", :first_name => "Ignacio", :last_name => "Alonso", :active => false)
Pilot.create(:id => 45, :full_name => "Jhonatan Ramos", :car => "Kart 125cc", :first_name => "Jhonatan", :last_name => "Ramos", :active => true)
Pilot.create(:id => 41, :full_name => "Joaquín Menoni", :car => "Kart 125cc", :first_name => "Joaquín", :last_name => "Menoni", :active => true)
Pilot.create(:id => 32, :full_name => "Jorge Mora", :car => "Formula VW", :first_name => "Jorge", :last_name => "Mora", :active => true)
Pilot.create(:id => 63, :full_name => "Jorge Moreno", :car => "Kart 125cc", :first_name => "Jorge", :last_name => "Moreno", :active => true)
Pilot.create(:id => 9, :full_name => "Jorge Parentini", :team => "JM Competición", :car => "Gol G2 1.8", :city => "Salto", :first_name => "Jorge", :last_name => "Parentini", :active => true)
Pilot.create(:id => 5, :full_name => "Jose  Luis Lura", :team => "Lura Competición", :car => "Gol G1 1.6", :city => "Salto", :first_name => "Jose  Luis", :last_name => "Lura", :active => true)
Pilot.create(:id => 20, :full_name => "Juan  Castro", :team => "-", :car => "Amazon G1 1.6", :city => "Salto", :first_name => "Juan ", :last_name => "Castro", :birth_date => Mon, 05 Apr 2010, :active => false)
Pilot.create(:id => 55, :full_name => "Juan Imas", :car => "Kart 125cc", :first_name => "Juan", :last_name => "Imas", :active => true)
Pilot.create(:id => 68, :full_name => "Juan Manuel Soto", :car => "Kart 125cc", :first_name => "Juan Manuel", :last_name => "Soto", :active => true)
Pilot.create(:id => 34, :full_name => "Leonardo Cavanna", :car => "Kart 125cc", :city => "Salto", :first_name => "Leonardo", :last_name => "Cavanna", :active => true)
Pilot.create(:id => 2, :full_name => "Leonel Nóbile", :team => "Usbeiuk Competicón", :car => "Gol G2 1.6", :city => "Paysandu", :first_name => "Leonel", :last_name => "Nóbile", :active => true)
Pilot.create(:id => 58, :full_name => "Luis A. Ganzo", :car => "Kart 125cc", :city => "Salto", :first_name => "Luis A.", :last_name => "Ganzo", :active => true)
Pilot.create(:id => 57, :full_name => "Luis A. Kucharsky", :car => "Kart 125cc", :city => "Salto", :first_name => "Luis A.", :last_name => "Kucharsky", :active => true)
Pilot.create(:id => 39, :full_name => "Luis Bidart", :car => "Kart 125cc", :city => "Salto", :first_name => "Luis", :last_name => "Bidart", :active => true)
Pilot.create(:id => 67, :full_name => "Luis Borba", :car => "Kart 125cc", :city => "Salto", :first_name => "Luis", :last_name => "Borba", :active => true)
Pilot.create(:id => 54, :full_name => "Manuel Bottaro", :car => "Kart 125cc", :first_name => "Manuel", :last_name => "Bottaro", :active => true)
Pilot.create(:id => 51, :full_name => "Marcelo Freitas", :car => "Kart 125cc", :city => "Salto", :first_name => "Marcelo", :last_name => "Freitas", :active => true)
Pilot.create(:id => 40, :full_name => "Marcelo Neron", :car => "Kart 125cc", :first_name => "Marcelo", :last_name => "Neron", :active => true)
Pilot.create(:id => 31, :full_name => "Marcelo Trazenco", :car => "Formula VW", :first_name => "Marcelo", :last_name => "Trazenco", :active => true)
Pilot.create(:id => 64, :full_name => "Marcel Petrib", :car => "Kart 125cc", :first_name => "Marcel", :last_name => "Petrib", :active => true)
Pilot.create(:id => 15, :full_name => "Marcos Aguiñagalde", :team => "-", :car => "Gol G2 1.6", :city => "Salto", :first_name => "Marcos", :last_name => "Aguiñagalde", :active => false)
Pilot.create(:id => 3, :full_name => "Marcos Dominguez", :team => "-", :car => "Amazon G1 1.6", :city => "Rivera", :first_name => "Marcos", :last_name => "Dominguez", :active => true)
Pilot.create(:id => 8, :full_name => "Mario Bonica", :team => "-", :car => "Gol G2 1.8", :city => "Paysandú", :first_name => "Mario", :last_name => "Bonica", :active => true)
Pilot.create(:id => 28, :full_name => "Mario  Tolstoy", :team => "-", :car => "Formula VW", :first_name => "Mario ", :last_name => "Tolstoy", :active => true)
Pilot.create(:id => 19, :full_name => "Martin Acosta", :team => "-", :car => "Gol G2 1.6", :city => "Tacuarembó", :first_name => "Martin", :last_name => "Acosta", :birth_date => Mon, 25 Jan 2010, :active => false)
Pilot.create(:id => 37, :full_name => "Matias Grilli", :car => "Kart 125cc", :city => "Salto", :first_name => "Matias", :last_name => "Grilli", :active => true)
Pilot.create(:id => 13, :full_name => "Miguel Taberne", :team => "-", :car => "Gol G2 1.6", :city => "Flores", :first_name => "Miguel", :last_name => "Taberne", :active => false)
Pilot.create(:id => 48, :full_name => "Natalia Legnazzi", :car => "Kart 125cc", :city => "Salto", :first_name => "Natalia", :last_name => "Legnazzi", :active => true)
Pilot.create(:id => 42, :full_name => "Natalia Pigurina", :car => "Kart 125cc", :city => "Salto", :first_name => "Natalia", :last_name => "Pigurina", :active => true)
Pilot.create(:id => 24, :full_name => "Nelson Machado", :team => "-", :car => "Gol 1.6", :city => "Salto", :first_name => "Nelson", :last_name => "Machado", :active => true)
Pilot.create(:id => 43, :full_name => "Nicolás Gallino", :team => "Ryng Competición", :car => "Kart 125cc", :city => "Salto", :first_name => "Nicolás", :last_name => "Gallino", :active => true)
Pilot.create(:id => 35, :full_name => "Pablo Siffredo", :team => "JM Competición", :car => "Kart 125cc", :city => "Salto", :first_name => "Pablo", :last_name => "Siffredo", :active => true)
Pilot.create(:id => 65, :full_name => "Paola Forrisi", :car => "Kart 125cc", :city => "Salto", :first_name => "Paola", :last_name => "Forrisi", :active => true)
Pilot.create(:id => 11, :full_name => "Renzo D' Acosta", :team => "-", :car => "Gol G2 1.8", :city => "Paysandú", :first_name => "Renzo", :last_name => "D' Acosta", :active => true)
Pilot.create(:id => 23, :full_name => "Roberto  Gallino", :team => "Ryng Competición", :car => "Gol 1.6", :city => "Salto", :first_name => "Roberto ", :last_name => "Gallino", :active => true)
Pilot.create(:id => 29, :full_name => "Roberto  Piastri", :team => "Lura Competición", :car => "Formula VW", :city => "Salto", :first_name => "Roberto ", :last_name => "Piastri", :active => true)
Pilot.create(:id => 22, :full_name => "Rodmey Bisio", :team => "Ryng Competición", :car => "Gol 1.6", :city => "Salto", :first_name => "Rodmey", :last_name => "Bisio", :active => true)
Pilot.create(:id => 49, :full_name => "Santiago Duran", :car => "Kart 125cc", :first_name => "Santiago", :last_name => "Duran", :active => true)
Pilot.create(:id => 14, :full_name => "Sergio De Brum", :team => "-", :car => "Gol G2 1.6", :city => "Yung", :first_name => "Sergio", :last_name => "De Brum", :active => true)
Pilot.create(:id => 46, :full_name => "Valentino Muffolini", :team => "JM Competición", :car => "Kart 125cc", :city => "Salto", :first_name => "Valentino", :last_name => "Muffolini", :active => true)
Pilot.create(:id => 52, :full_name => "Valerio Correa", :car => "Kart 125cc", :city => "Bella Unión", :first_name => "Valerio", :last_name => "Correa", :active => true)
Pilot.create(:id => 50, :full_name => "Willson Botti", :car => "Kart 125cc", :first_name => "Willson", :last_name => "Botti", :active => true)
