Race.create(:id => 12, :championship_id => 3, :city => "Tacuarembó", :date => Sun, 19 May 2013, :name => "Ciudad Tacuarembó", :done => true, :circuit_id => 4)
Race.create(:id => 13, :championship_id => 3, :city => "Salto", :date => Sun, 16 Jun 2013, :name => "Copa Ciudad Salto", :done => true, :circuit_id => 1)
Race.create(:id => 14, :championship_id => 3, :city => "Tacuarembó", :date => Sun, 11 Aug 2013, :name => "Ciudad Tacuarembó", :done => true, :circuit_id => 4)
Race.create(:id => 15, :championship_id => 3, :city => "Salto", :date => Sun, 08 Sep 2013, :name => "Ciudad Salto", :observation => "La clasificación final se define por el  orden de la serie de clasificación", :done => true, :circuit_id => 1)
Race.create(:id => 16, :championship_id => 3, :city => "Tacuarembó", :date => Sun, 20 Oct 2013, :name => "Ciudad Tacuarembó", :done => true, :circuit_id => 4)
Race.create(:id => 17, :championship_id => 3, :city => "Salto", :date => Sun, 24 Nov 2013, :name => "Copa Ciudad de Salto", :done => true, :circuit_id => 1)
Race.create(:id => 7, :championship_id => 2, :city => "Salto", :date => Sun, 15 Jun 2014, :name => "Gran Premio Roberto Piegas", :observation => "Clasificación final se desempata por mejor tiempo en clasificaón.", :done => true, :circuit_id => 1)
Race.create(:id => 18, :championship_id => 4, :city => "Salto", :date => Sun, 15 Jun 2014, :name => "Gran Premio Roberto Piegas", :observation => "Los competidores invitados no llevan puntaje para el Campeonato (Brizuela, Tolstoy y Castro)", :done => true, :circuit_id => 1)
Race.create(:id => 29, :championship_id => 6, :city => "Salto", :date => Sun, 15 Jun 2014, :name => "Gran Premio Roberto Piegas", :observation => "Ezequiel Borba (Nº 48) y Natalia Legnazzi (Nº 66) fueron descalificados por no cumplir con requisitos técnicos y de pesaje", :done => true, :circuit_id => 6)
Race.create(:id => 30, :championship_id => 6, :city => "Salto", :date => Sun, 27 Jul 2014, :name => "Gran Premio Roberto Piegas", :observation => "El punto obtenido por Natalia Legnazzi (kart Nº 48) no se tuvo en cuenta ya que dicho Nº no correspondía.", :done => true, :circuit_id => 6)
Race.create(:id => 19, :championship_id => 4, :city => "Salto", :date => Sun, 27 Jul 2014, :name => "Gran Premio Roberto Piegas", :done => true, :circuit_id => 1)
Race.create(:id => 8, :championship_id => 2, :city => "Salto", :date => Sun, 27 Jul 2014, :name => "Gran Premio Roberto Piegas", :done => true, :circuit_id => 1)
Race.create(:id => 20, :championship_id => 4, :city => "Salto", :date => Sun, 17 Aug 2014, :name => "Gran Premio Erneso Barcia", :done => true, :circuit_id => 1)
Race.create(:id => 31, :championship_id => 6, :city => "Salto", :date => Sun, 17 Aug 2014, :name => "Gran Premio Erneso Barcia", :done => true, :circuit_id => 6)
Race.create(:id => 9, :championship_id => 2, :city => "Salto", :date => Sun, 17 Aug 2014, :name => "Gran Premio Ernesto Barcia", :observation => "Germán Fagalde (auto No 15) descalificado por técnica.", :done => true, :circuit_id => 1)
Race.create(:id => 32, :championship_id => 6, :city => "Paysandú", :date => Sun, 21 Sep 2014, :name => "Gran Premio Ciudad Paysandú", :done => true, :circuit_id => 7)
Race.create(:id => 10, :championship_id => 2, :city => "Paysandú", :date => Sun, 21 Sep 2014, :name => "Gran Premio Ciudad Paysandú", :done => true, :circuit_id => 2)
Race.create(:id => 21, :championship_id => 4, :city => "Paysandú", :date => Sun, 21 Sep 2014, :name => "Gran Premio Ciudad Paysandú", :done => true, :circuit_id => 2)
Race.create(:id => 22, :championship_id => 4, :city => "Salto", :date => Sun, 12 Oct 2014, :name => "Gran Premio Victorino Muffolini", :observation => "En controles finales, la Comisión Técnica descalificó al competidor Roberto Piastri (auto Nº 7) por Venturis", :done => true, :circuit_id => 1)
Race.create(:id => 33, :championship_id => 6, :city => "Salto", :date => Sun, 12 Oct 2014, :name => "Gran Premio Victorino Muffolini", :done => true, :circuit_id => 6)
Race.create(:id => 11, :championship_id => 2, :city => "Salto", :date => Sun, 12 Oct 2014, :name => "Gran Premio Victorino Muffolini", :done => true, :circuit_id => 1)
Race.create(:id => 40, :championship_id => 8, :city => "Salto", :date => Sun, 12 Jul 2015, :name => "Copa Ciudad de Salto", :done => true, :circuit_id => 6)
Race.create(:id => 1, :championship_id => 1, :city => "Salto", :date => Sun, 12 Jul 2015, :name => "Copa Ciudad de Salto", :done => true, :circuit_id => 1)
Race.create(:id => 23, :championship_id => 5, :city => "Salto", :date => Sun, 12 Jul 2015, :name => "Copa Ciudad de Salto", :done => true, :circuit_id => 1)
Race.create(:id => 34, :championship_id => 7, :city => "Salto", :date => Sun, 12 Jul 2015, :name => "Copa Ciudad de Salto", :done => true, :circuit_id => 6)
Race.create(:id => 35, :championship_id => 7, :city => "Salto", :date => Sun, 09 Aug 2015, :name => "Gran Premio 77 Años SAC", :circuit_id => 6)
Race.create(:id => 24, :championship_id => 5, :city => "Salto", :date => Sun, 09 Aug 2015, :name => "Gran Premio 77 Años SAC", :observation => "No 7 C.Lura no tenía la indumentaria obligatoria y salió a pista, por lo cual fue excluido de clasificación, 1ra. Serie y 2da. Serie. Podrá largar la final en penúltimo lugar.\r\nEl No 18 M.Traszenko no tenía la indumentaria obligatoria y salió a pista, por lo cual fue excluido de clasificación, 1ra. Serie y 2da. Serie. Podía largar la final en último lugar.", :done => true, :circuit_id => 1)
Race.create(:id => 41, :championship_id => 8, :city => "Salto", :date => Sun, 09 Aug 2015, :name => "Gran Premio 77 Años SAC", :circuit_id => 6)
Race.create(:id => 2, :championship_id => 1, :city => "Salto", :date => Sun, 09 Aug 2015, :name => "Copa Ciudad de Salto", :observation => "El No 7 C.Lura no tenía la indumentaria oblig. y salió a pista en Fórmula SAC, por lo cual fue excluido de clasificación, 1ra. Serie y 2da. Serie. Largo la final en último lugar.\r\nEl competidor No 71 M.Bonica fue excluido de toda la etapa por no respetar reglamentación sobre sorteo de levas.", :done => true, :circuit_id => 1)
Race.create(:id => 42, :championship_id => 8, :city => "Paysandú", :date => Sun, 13 Sep 2015, :name => "Copa Ciudad de Paysandú", :circuit_id => 7)
Race.create(:id => 36, :championship_id => 7, :city => "Paysandú", :date => Sun, 13 Sep 2015, :name => "Copa Ciudad de Paysandú", :circuit_id => 7)
Race.create(:id => 3, :championship_id => 1, :city => "Paysandu", :date => Sun, 13 Sep 2015, :name => "Copa Ciudad de Paysandú", :done => true, :circuit_id => 2)
Race.create(:id => 25, :championship_id => 5, :city => "Paysandú", :date => Sun, 13 Sep 2015, :name => "Copa Ciudad de Paysandú", :done => true, :circuit_id => 2)
Race.create(:id => 43, :championship_id => 8, :city => "Salto", :date => Sun, 04 Oct 2015, :name => "Gran Premio Ciudad Salto", :circuit_id => 1)
Race.create(:id => 37, :championship_id => 7, :city => "Salto", :date => Sun, 04 Oct 2015, :name => "Copa Ciudad de Salto ", :circuit_id => 6)
Race.create(:id => 4, :championship_id => 1, :city => "Salto", :date => Sun, 04 Oct 2015, :name => "Copa Ciudad de Salto", :circuit_id => 1)
Race.create(:id => 26, :championship_id => 5, :city => "Salto", :date => Sun, 04 Oct 2015, :name => "Gran Premio Ciudad Salto", :circuit_id => 1)
Race.create(:id => 44, :championship_id => 8, :city => "Paysandu", :date => Sun, 25 Oct 2015, :name => "Copa Ciudad de Paysandú", :circuit_id => 7)
Race.create(:id => 5, :championship_id => 1, :city => "Paysandú", :date => Sun, 25 Oct 2015, :name => "Copa Ciudad Paysandú", :circuit_id => 2)
Race.create(:id => 27, :championship_id => 5, :city => "Paysandú", :date => Sun, 25 Oct 2015, :name => "Copa Ciudad de Paysandú", :circuit_id => 2)
Race.create(:id => 38, :championship_id => 7, :city => "Paysandú", :date => Sun, 25 Oct 2015, :name => "Gran Premio Ciudad Paysandú", :circuit_id => 7)
Race.create(:id => 6, :championship_id => 1, :city => "Salto", :date => Sun, 01 Nov 2015, :name => "Copa Ciudad de Salto", :circuit_id => 1)
Race.create(:id => 28, :championship_id => 5, :city => "Salto", :date => Sun, 01 Nov 2015, :name => "Copa Ciudad de Salto", :circuit_id => 1)
Race.create(:id => 39, :championship_id => 7, :city => "Salto", :date => Sun, 01 Nov 2015, :name => "Copa Ciudad de Salto", :circuit_id => 6)
Race.create(:id => 45, :championship_id => 8, :city => "Salto", :date => Sun, 01 Nov 2015, :name => "Copa Ciudad de Salto", :circuit_id => 6)
