Step.create(:id => 77, :race_id => 32, :number => 0, :name => "Clasificación")
Step.create(:id => 69, :race_id => 23, :number => 0, :name => "Clasificación")
Step.create(:id => 73, :race_id => 33, :number => 0, :name => "Clasificación", :observation => "Se lo pasó al ultimo lugar al competidor Cavanna (Nº 50) por cambio de motor (de 7 a 16).")
Step.create(:id => 49, :race_id => 18, :number => 0, :name => "Clasificación", :observation => "La clasificación fue por sorteo (no hubo puntaje de pole)")
Step.create(:id => 85, :race_id => 30, :number => 0, :name => "Clasificación")
Step.create(:id => 103, :race_id => 24, :number => 0, :name => "Clasificación")
Step.create(:id => 81, :race_id => 31, :number => 0, :name => "Clasificación", :observation => "Por desición de Comisión Técnica, no se tuvo en cuenta el tiempo del Nº 21 Luis Ganzo (49:90), largó 1ra. Serie en último lugar")
Step.create(:id => 5, :race_id => 8, :number => 0, :name => "Clasificación")
Step.create(:id => 102, :race_id => 2, :number => 0, :name => "Final")
Step.create(:id => 9, :race_id => 10, :number => 0, :name => "Clasificación")
Step.create(:id => 101, :race_id => 2, :number => 0, :name => "Segunda Serie")
Step.create(:id => 37, :race_id => 17, :number => 0, :name => "Clasificación")
Step.create(:id => 100, :race_id => 2, :number => 0, :name => "Primer Serie")
Step.create(:id => 41, :race_id => 16, :number => 0, :name => "Clasificación")
Step.create(:id => 99, :race_id => 2, :number => 0, :name => "Clasificación")
Step.create(:id => 29, :race_id => 13, :number => 0, :name => "Clasificación")
Step.create(:id => 45, :race_id => 15, :number => 0, :name => "Clasificación", :observation => "El punto de poleman no se otorga por que fue a soprteo.")
Step.create(:id => 25, :race_id => 12, :number => 0, :name => "Clasificación")
Step.create(:id => 21, :race_id => 9, :number => 0, :name => "Clasificación")
Step.create(:id => 107, :race_id => 3, :number => 0, :name => "Clasificación")
Step.create(:id => 96, :race_id => 40, :number => 0, :name => "Clasificación")
Step.create(:id => 13, :race_id => 7, :number => 0, :name => "Clasificación")
Step.create(:id => 93, :race_id => 34, :number => 0, :name => "Clasificación", :observation => "P.Siffredo No 13 y R. Gallino No 41 se los recarga con dos puestos x abandonar Parque Cerrado sin autorización.\r\nNo 35 V.Muffolini se lo excluye por no llegar al peso mínimo.\r\nNo 33 A.Parentini se lo recarga con dos puestos x abandonar P.C. sin autorización y se lo apercibe por maniobra incorrecta en perjuicio del No 39 Luis Ganzo.\r\n")
Step.create(:id => 53, :race_id => 19, :number => 0, :name => "Clasificación")
Step.create(:id => 111, :race_id => 25, :number => 0, :name => "Clasificación")
Step.create(:id => 17, :race_id => 11, :number => 0, :name => "Clasificación", :observation => "Bruno Mori (auto No 21) se recarga con dos puestos por sanción en 4ta fecha ")
Step.create(:id => 57, :race_id => 20, :number => 0, :name => "Clasificación")
Step.create(:id => 89, :race_id => 29, :number => 0, :name => "Clasificación", :observation => "La clasificación fue por sorteo (no hubo puntaje de pole)")
Step.create(:id => 61, :race_id => 21, :number => 0, :name => "Clasificación")
Step.create(:id => 1, :race_id => 1, :number => 0, :name => "Clasificación")
Step.create(:id => 65, :race_id => 22, :number => 0, :name => "Clasificación")
Step.create(:id => 33, :race_id => 14, :number => 0, :name => "Clasificación")
Step.create(:id => 104, :race_id => 24, :number => 1, :name => "Primer Serie")
Step.create(:id => 6, :race_id => 8, :number => 1, :name => "Primer Serie")
Step.create(:id => 22, :race_id => 9, :number => 1, :name => "Primer Serie", :observation => " Bruno Mori (auto Nº 21) se le mostró bandera de apercibimiento por maniobra peligrosa")
Step.create(:id => 66, :race_id => 22, :number => 1, :name => "Primer Serie")
Step.create(:id => 58, :race_id => 20, :number => 1, :name => "Primer Serie")
Step.create(:id => 90, :race_id => 29, :number => 1, :name => "Primer Serie")
Step.create(:id => 38, :race_id => 17, :number => 1, :name => "Primer Serie")
Step.create(:id => 70, :race_id => 23, :number => 1, :name => "Primer Serie")
Step.create(:id => 14, :race_id => 7, :number => 1, :name => "Primer Serie", :observation => "Germán Fagalde (auto No 15) se recarga con dos puestos por un toque.")
Step.create(:id => 112, :race_id => 25, :number => 1, :name => "Primer Serie")
Step.create(:id => 74, :race_id => 33, :number => 1, :name => "Primer Serie", :observation => "Se mostró bandera negra y fue excluido el karting Nº 17 (Menoni) por problemas en fijación de pesas.Tampoco dió con pesaje reglamentario.")
Step.create(:id => 46, :race_id => 15, :number => 1, :name => "Primer Serie")
Step.create(:id => 86, :race_id => 30, :number => 1, :name => "Primer Serie")
Step.create(:id => 62, :race_id => 21, :number => 1, :name => "Primer Serie")
Step.create(:id => 78, :race_id => 32, :number => 1, :name => "Primer Serie", :observation => "El karting Nº 20 (A.Bidart) fue sancionado con 10 puestos (de 1º a 11º) por toque al karting Nº 50 (Cavanna) ")
Step.create(:id => 50, :race_id => 18, :number => 1, :name => "Primer Serie")
Step.create(:id => 54, :race_id => 19, :number => 1, :name => "Primer Serie")
Step.create(:id => 108, :race_id => 3, :number => 1, :name => "Primer Serie")
Step.create(:id => 82, :race_id => 31, :number => 1, :name => "Primer Serie")
Step.create(:id => 97, :race_id => 40, :number => 1, :name => "Primer Serie")
Step.create(:id => 2, :race_id => 1, :number => 1, :name => "Primer Serie", :observation => "Jorge Parentini (auto No 33) se le recarga un puesto x adelantamiento en largada.\r\nGermán Fagalde (auto No 15) y Leonel Nobile (auto No 1): ambos excluidos de 1ra. Serie x no concurrir a Técnica")
Step.create(:id => 94, :race_id => 34, :number => 1, :name => "Primer Serie")
Step.create(:id => 42, :race_id => 16, :number => 1, :name => "Primer Serie", :observation => "Jose Luis Lura (auto No 7) recargado con puestos.")
Step.create(:id => 26, :race_id => 12, :number => 1, :name => "Primer Serie")
Step.create(:id => 18, :race_id => 11, :number => 1, :name => "Primer Serie")
Step.create(:id => 10, :race_id => 10, :number => 1, :name => "Primer Serie")
Step.create(:id => 30, :race_id => 13, :number => 1, :name => "Primer Serie")
Step.create(:id => 34, :race_id => 14, :number => 1, :name => "Primer Serie")
Step.create(:id => 59, :race_id => 20, :number => 2, :name => "Segunda Serie")
Step.create(:id => 3, :race_id => 1, :number => 2, :name => "Segunda Serie")
Step.create(:id => 19, :race_id => 11, :number => 2, :name => "Segunda Serie", :observation => "Bandera de apercibimiento a los autos Nº 11 (Piastri) y Nº 21 (Mori). No se determinaron sanciones.")
Step.create(:id => 7, :race_id => 8, :number => 2, :name => "Segunda Serie", :observation => "Mario Bonica (auto No 06) excluido por maniobras antideportivas.")
Step.create(:id => 11, :race_id => 10, :number => 2, :name => "Segunda Serie")
Step.create(:id => 51, :race_id => 18, :number => 2, :name => "Segunda Serie")
Step.create(:id => 15, :race_id => 7, :number => 2, :name => "Segunda Serie", :observation => "Jose Luis Lura (auto No 7) descalificado por maniobra.")
Step.create(:id => 27, :race_id => 12, :number => 2, :name => "Segunda Serie")
Step.create(:id => 35, :race_id => 14, :number => 2, :name => "Segunda Serie")
Step.create(:id => 39, :race_id => 17, :number => 2, :name => "Segunda Serie")
Step.create(:id => 43, :race_id => 16, :number => 2, :name => "Segunda Serie")
Step.create(:id => 31, :race_id => 13, :number => 2, :name => "Segunda Serie")
Step.create(:id => 47, :race_id => 15, :number => 2, :name => "Segunda Serie")
Step.create(:id => 23, :race_id => 9, :number => 2, :name => "Segunda Serie")
Step.create(:id => 55, :race_id => 19, :number => 2, :name => "Segunda Serie")
Step.create(:id => 63, :race_id => 21, :number => 2, :name => "Segunda Serie")
Step.create(:id => 67, :race_id => 22, :number => 2, :name => "Segunda Serie")
Step.create(:id => 71, :race_id => 23, :number => 2, :name => "Segunda Serie", :observation => "Auto N° 3 Gabino Franco Fraguas excluido por recibir ayuda externa en pista.")
Step.create(:id => 75, :race_id => 33, :number => 2, :name => "Segunda Serie")
Step.create(:id => 79, :race_id => 32, :number => 2, :name => "Segunda Serie", :observation => "Se le mostró bandera negra al karting Nº 42 (Moreno) por conducta antideportiva y fue excluido.Tampoco concurrió al pesaje.")
Step.create(:id => 83, :race_id => 31, :number => 2, :name => "Segunda Serie")
Step.create(:id => 87, :race_id => 30, :number => 2, :name => "Segunda Serie")
Step.create(:id => 91, :race_id => 29, :number => 2, :name => "Segunda Serie")
Step.create(:id => 95, :race_id => 34, :number => 2, :name => "Segunda Serie", :observation => "V.Muffolini No 35 recarga con un puesto por adelantaminto en largada.")
Step.create(:id => 98, :race_id => 40, :number => 2, :name => "Segunda Serie")
Step.create(:id => 105, :race_id => 24, :number => 2, :name => "Segunda Serie", :observation => "A R.Bisio (auto No 2) se le recarga un puesto x salir de fila en línea de sentencia en relargada auto seguridad (paso de 1ro. a 2do.).\r\nEl No 3 G.Franco Fraguas no sumó puntos porque registró solo 3 vueltas")
Step.create(:id => 109, :race_id => 3, :number => 2, :name => "Segunda Serie")
Step.create(:id => 113, :race_id => 25, :number => 2, :name => "Segunda Serie")
Step.create(:id => 92, :race_id => 29, :number => 3, :name => "Final")
Step.create(:id => 64, :race_id => 21, :number => 3, :name => "Final")
Step.create(:id => 60, :race_id => 20, :number => 3, :name => "Final")
Step.create(:id => 56, :race_id => 19, :number => 3, :name => "Final", :observation => "No se larga la serie final")
Step.create(:id => 24, :race_id => 9, :number => 3, :name => "Final")
Step.create(:id => 48, :race_id => 15, :number => 3, :name => "Final")
Step.create(:id => 110, :race_id => 3, :number => 3, :name => "Final", :observation => "El competidor Nº 7 J. L. Lura fue penailzado con dos puestos.")
Step.create(:id => 32, :race_id => 13, :number => 3, :name => "Final")
Step.create(:id => 44, :race_id => 16, :number => 3, :name => "Final")
Step.create(:id => 4, :race_id => 1, :number => 3, :name => "Final")
Step.create(:id => 40, :race_id => 17, :number => 3, :name => "Final")
Step.create(:id => 36, :race_id => 14, :number => 3, :name => "Final")
Step.create(:id => 28, :race_id => 12, :number => 3, :name => "Final")
Step.create(:id => 52, :race_id => 18, :number => 3, :name => "Final")
Step.create(:id => 16, :race_id => 7, :number => 3, :name => "Final")
Step.create(:id => 72, :race_id => 23, :number => 3, :name => "Final")
Step.create(:id => 12, :race_id => 10, :number => 3, :name => "Final", :observation => "Bruno Mori ( auto Nº 21) ) cierra radio de giro al auto Nº 7 (Lura). En la próx. carrera, el auto Nº 21 (Mori) sea retrasado 2 lugares en la prueba de clasificación.\r\nJose Luis Lura (auto No 6) no cumple el 50% de las vueltas, no suma puntos.")
Step.create(:id => 106, :race_id => 24, :number => 3, :name => "Final")
Step.create(:id => 20, :race_id => 11, :number => 3, :name => "Final", :observation => "Bandera negra a los competidores Errea (Nº 111) y Mori (Nº 21) por conducta antideportiva. Excluidos de la Serie.")
Step.create(:id => 84, :race_id => 31, :number => 3, :name => "Final")
Step.create(:id => 80, :race_id => 32, :number => 3, :name => "Final", :observation => "Nueva conducta antideportiva del karting Nº 42 con el karting Nº 20 (A.Bidart) lo cual deja a los 2 pilotos fuera de carrera. \r\nEn dicha incidencia, el piloto Moreno baja del karting e intenta agredir al competidor A.Bidart y fue neutralizado por las autoridades de pista. \r\nAdemás, no pesó el karting ni en la 2da. serie ni en la final, por lo cual las Autoridades determinaron la descalificación de la prueba.")
Step.create(:id => 76, :race_id => 33, :number => 3, :name => "Final", :observation => "Se lo pasó al ultimo lugar de la grilla al competidor Cavanna (Nº 50) por cambio de motor (de 7 a 16).")
Step.create(:id => 8, :race_id => 8, :number => 3, :name => "Final")
Step.create(:id => 88, :race_id => 30, :number => 3, :name => "Final")
Step.create(:id => 68, :race_id => 22, :number => 3, :name => "Final")
Step.create(:id => 114, :race_id => 25, :number => 3, :name => "Final")
