development:
  adapter: postgresql
  database: sac_development
  host: localhost
  username: postgres
  password: password

test:
  adapter: postgresql
  database: sac_test
  host: localhost
  username: postgres
  password: password

production:
  port: 5432
  host: ec2-54-243-47-213.compute-1.amazonaws.com
  adapter: postgresql
  encoding: unicode
  database: d1eg0ao4putcmm
  pool: 5
  username: fyjsvgkbclieve
  password: ELXkpMCk_45Ea0mgKrSTAwvPrp
