development:
  adapter: postgresql
  database: sac_development
  host: localhost
  username: postgres
  password: password

test:
  adapter: postgresql
  database: sac_test
  host: localhost
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: sac_production
  pool: 5
  username: postgres
  password: password
